/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.0-59-gfeee78d

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "OD.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
OD_ATTR_PERSIST_COMM OD_PERSIST_COMM_t OD_PERSIST_COMM = {
    .x1000_deviceType = 0x00000000,
    .x1005_COB_ID_SYNCMessage = 0x00000080,
    .x1006_communicationCyclePeriod = 0x00000000,
    .x1007_synchronousWindowLength = 0x00000000,
    .x1012_COB_IDTimeStampObject = 0x00000100,
    .x1014_COB_ID_EMCY = 0x00000080,
    .x1015_inhibitTimeEMCY = 0x0000,
    .x1016_consumerHeartbeatTime_sub0 = 0x08,
    .x1016_consumerHeartbeatTime = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x1017_producerHeartbeatTime = 0x009B,
    .x1018_identity = {
        .highestSub_indexSupported = 0x04,
        .vendor_ID = 0x00000000,
        .productCode = 0x00000000,
        .revisionNumber = 0x00000000,
        .serialNumber = 0x00000000
    },
    .x1019_synchronousCounterOverflowValue = 0x00,
    .x1280_SDOClientParameter = {
        .highestSub_indexSupported = 0x03,
        .COB_IDClientToServerTx = 0x80000000,
        .COB_IDServerToClientRx = 0x80000000,
        .node_IDOfTheSDOServer = 0x01
    },
    .x1400_RPDOCommunicationParameter = {
        .maxSub_index = 0x06,
        .COB_IDUsedByRPDO = 0x00000281,
        .transmissionType = 0xFE
    },
    .x1600_RPDOMappingParameter = {
        .numberOfMappedObjects = 0x04,
        .mappedObject_1 = 0x22000010,
        .mappedObject_2 = 0x22010010,
        .mappedObject_3 = 0x22020010,
        .mappedObject_4 = 0x22030010
    },
    .x1800_TPDOCommunicationParameter = {
        .maxSub_index = 0x06,
        .COB_IDUsedByTPDO = 0x00000183,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .compatibilityEntry = 0x00,
        .eventTimer = 0x00C8,
        .SYNCStartValue = 0x00
    },
    .x1A00_TPDOMappingParameter = {
        .numberOfMappedObjects = 0x03,
        .mappedObject_1 = 0x23000010,
        .mappedObject_2 = 0x23010010,
        .mappedObject_3 = 0x23020008
    }
};

OD_ATTR_RAM OD_RAM_t OD_RAM = {
    .x1001_errorRegister = 0x00,
    .x1010_storeParameters_sub0 = 0x04,
    .x1010_storeParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1011_restoreDefaultParameters_sub0 = 0x04,
    .x1011_restoreDefaultParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1200_SDOServerParameter = {
        .highestSub_indexSupported = 0x02,
        .COB_IDClientToServerRx = 0x00000600,
        .COB_IDServerToClientTx = 0x00000580
    },
    .x2000_ACTION_ID = 0x0000,
    .x2001_param_1 = 0,
    .x2002_param_2 = 0,
    .x2003_param_3 = 0,
    .x2004_param_4 = 0,
    .x2005_param_5 = 0,
    .x2006_param_6 = 0,
    .x2007_command_ID = 0x0000,
    .x2100_current_command_status = 0x00,
    .x2101_current_command_id = 0x0000,
    .x2102_current_action_id = 0x0000,
    .x2103_last_completed_command_id = 0x0000,
    .x2104_command_error_code = 0x00,
    .x2200_pos_robot_x = 0,
    .x2201_pos_robot_y = 0,
    .x2202_pos_robot_theta = 0,
    .x2203_lin_vel_robot = 0,
    .x2300_pos_robot_adversaire_x = 0x0000,
    .x2301_pos_robot_adversaire_y = 0x0000,
    .x2302_status_carte_lidar = 0x00
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_array_t o_1003_pre_definedErrorField;
    OD_obj_var_t o_1005_COB_ID_SYNCMessage;
    OD_obj_var_t o_1006_communicationCyclePeriod;
    OD_obj_var_t o_1007_synchronousWindowLength;
    OD_obj_array_t o_1010_storeParameters;
    OD_obj_array_t o_1011_restoreDefaultParameters;
    OD_obj_var_t o_1012_COB_IDTimeStampObject;
    OD_obj_var_t o_1014_COB_ID_EMCY;
    OD_obj_var_t o_1015_inhibitTimeEMCY;
    OD_obj_array_t o_1016_consumerHeartbeatTime;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identity[5];
    OD_obj_var_t o_1019_synchronousCounterOverflowValue;
    OD_obj_record_t o_1200_SDOServerParameter[3];
    OD_obj_record_t o_1280_SDOClientParameter[4];
    OD_obj_record_t o_1400_RPDOCommunicationParameter[3];
    OD_obj_record_t o_1600_RPDOMappingParameter[5];
    OD_obj_record_t o_1800_TPDOCommunicationParameter[7];
    OD_obj_record_t o_1A00_TPDOMappingParameter[4];
    OD_obj_var_t o_2000_ACTION_ID;
    OD_obj_var_t o_2001_param_1;
    OD_obj_var_t o_2002_param_2;
    OD_obj_var_t o_2003_param_3;
    OD_obj_var_t o_2004_param_4;
    OD_obj_var_t o_2005_param_5;
    OD_obj_var_t o_2006_param_6;
    OD_obj_var_t o_2007_command_ID;
    OD_obj_var_t o_2100_current_command_status;
    OD_obj_var_t o_2101_current_command_id;
    OD_obj_var_t o_2102_current_action_id;
    OD_obj_var_t o_2103_last_completed_command_id;
    OD_obj_var_t o_2104_command_error_code;
    OD_obj_var_t o_2200_pos_robot_x;
    OD_obj_var_t o_2201_pos_robot_y;
    OD_obj_var_t o_2202_pos_robot_theta;
    OD_obj_var_t o_2203_lin_vel_robot;
    OD_obj_var_t o_2300_pos_robot_adversaire_x;
    OD_obj_var_t o_2301_pos_robot_adversaire_y;
    OD_obj_var_t o_2302_status_carte_lidar;
} ODObjs_t;

static CO_PROGMEM ODObjs_t ODObjs = {
    .o_1000_deviceType = {
        .dataOrig = &OD_PERSIST_COMM.x1000_deviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = &OD_RAM.x1001_errorRegister,
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataLength = 1
    },
    .o_1003_pre_definedErrorField = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1005_COB_ID_SYNCMessage = {
        .dataOrig = &OD_PERSIST_COMM.x1005_COB_ID_SYNCMessage,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1006_communicationCyclePeriod = {
        .dataOrig = &OD_PERSIST_COMM.x1006_communicationCyclePeriod,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1007_synchronousWindowLength = {
        .dataOrig = &OD_PERSIST_COMM.x1007_synchronousWindowLength,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1010_storeParameters = {
        .dataOrig0 = &OD_RAM.x1010_storeParameters_sub0,
        .dataOrig = &OD_RAM.x1010_storeParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1011_restoreDefaultParameters = {
        .dataOrig0 = &OD_RAM.x1011_restoreDefaultParameters_sub0,
        .dataOrig = &OD_RAM.x1011_restoreDefaultParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1012_COB_IDTimeStampObject = {
        .dataOrig = &OD_PERSIST_COMM.x1012_COB_IDTimeStampObject,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1014_COB_ID_EMCY = {
        .dataOrig = &OD_PERSIST_COMM.x1014_COB_ID_EMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1015_inhibitTimeEMCY = {
        .dataOrig = &OD_PERSIST_COMM.x1015_inhibitTimeEMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1016_consumerHeartbeatTime = {
        .dataOrig0 = &OD_PERSIST_COMM.x1016_consumerHeartbeatTime_sub0,
        .dataOrig = &OD_PERSIST_COMM.x1016_consumerHeartbeatTime[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &OD_PERSIST_COMM.x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identity = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.vendor_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.productCode,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.revisionNumber,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.serialNumber,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1019_synchronousCounterOverflowValue = {
        .dataOrig = &OD_PERSIST_COMM.x1019_synchronousCounterOverflowValue,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_1200_SDOServerParameter = {
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.COB_IDClientToServerRx,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.COB_IDServerToClientTx,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1280_SDOClientParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.COB_IDClientToServerTx,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.COB_IDServerToClientRx,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.node_IDOfTheSDOServer,
            .subIndex = 3,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1400_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.maxSub_index,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1600_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.numberOfMappedObjects,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.mappedObject_1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.mappedObject_2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.mappedObject_3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.mappedObject_4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1800_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.maxSub_index,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.compatibilityEntry,
            .subIndex = 4,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1A00_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.numberOfMappedObjects,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.mappedObject_1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.mappedObject_2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.mappedObject_3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_2000_ACTION_ID = {
        .dataOrig = &OD_RAM.x2000_ACTION_ID,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2001_param_1 = {
        .dataOrig = &OD_RAM.x2001_param_1,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2002_param_2 = {
        .dataOrig = &OD_RAM.x2002_param_2,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2003_param_3 = {
        .dataOrig = &OD_RAM.x2003_param_3,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2004_param_4 = {
        .dataOrig = &OD_RAM.x2004_param_4,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2005_param_5 = {
        .dataOrig = &OD_RAM.x2005_param_5,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2006_param_6 = {
        .dataOrig = &OD_RAM.x2006_param_6,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2007_command_ID = {
        .dataOrig = &OD_RAM.x2007_command_ID,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2100_current_command_status = {
        .dataOrig = &OD_RAM.x2100_current_command_status,
        .attribute = ODA_SDO_RW | ODA_TPDO,
        .dataLength = 1
    },
    .o_2101_current_command_id = {
        .dataOrig = &OD_RAM.x2101_current_command_id,
        .attribute = ODA_SDO_RW | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2102_current_action_id = {
        .dataOrig = &OD_RAM.x2102_current_action_id,
        .attribute = ODA_SDO_RW | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2103_last_completed_command_id = {
        .dataOrig = &OD_RAM.x2103_last_completed_command_id,
        .attribute = ODA_SDO_RW | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2104_command_error_code = {
        .dataOrig = &OD_RAM.x2104_command_error_code,
        .attribute = ODA_SDO_RW | ODA_TPDO,
        .dataLength = 1
    },
    .o_2200_pos_robot_x = {
        .dataOrig = &OD_RAM.x2200_pos_robot_x,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2201_pos_robot_y = {
        .dataOrig = &OD_RAM.x2201_pos_robot_y,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2202_pos_robot_theta = {
        .dataOrig = &OD_RAM.x2202_pos_robot_theta,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2203_lin_vel_robot = {
        .dataOrig = &OD_RAM.x2203_lin_vel_robot,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2300_pos_robot_adversaire_x = {
        .dataOrig = &OD_RAM.x2300_pos_robot_adversaire_x,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2301_pos_robot_adversaire_y = {
        .dataOrig = &OD_RAM.x2301_pos_robot_adversaire_y,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_2302_status_carte_lidar = {
        .dataOrig = &OD_RAM.x2302_status_carte_lidar,
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataLength = 1
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static OD_ATTR_OD OD_entry_t ODList[] = {
    {0x1000, 0x01, ODT_VAR, &ODObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &ODObjs.o_1001_errorRegister, NULL},
    {0x1003, 0x11, ODT_ARR, &ODObjs.o_1003_pre_definedErrorField, NULL},
    {0x1005, 0x01, ODT_VAR, &ODObjs.o_1005_COB_ID_SYNCMessage, NULL},
    {0x1006, 0x01, ODT_VAR, &ODObjs.o_1006_communicationCyclePeriod, NULL},
    {0x1007, 0x01, ODT_VAR, &ODObjs.o_1007_synchronousWindowLength, NULL},
    {0x1010, 0x05, ODT_ARR, &ODObjs.o_1010_storeParameters, NULL},
    {0x1011, 0x05, ODT_ARR, &ODObjs.o_1011_restoreDefaultParameters, NULL},
    {0x1012, 0x01, ODT_VAR, &ODObjs.o_1012_COB_IDTimeStampObject, NULL},
    {0x1014, 0x01, ODT_VAR, &ODObjs.o_1014_COB_ID_EMCY, NULL},
    {0x1015, 0x01, ODT_VAR, &ODObjs.o_1015_inhibitTimeEMCY, NULL},
    {0x1016, 0x09, ODT_ARR, &ODObjs.o_1016_consumerHeartbeatTime, NULL},
    {0x1017, 0x01, ODT_VAR, &ODObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &ODObjs.o_1018_identity, NULL},
    {0x1019, 0x01, ODT_VAR, &ODObjs.o_1019_synchronousCounterOverflowValue, NULL},
    {0x1200, 0x03, ODT_REC, &ODObjs.o_1200_SDOServerParameter, NULL},
    {0x1280, 0x04, ODT_REC, &ODObjs.o_1280_SDOClientParameter, NULL},
    {0x1400, 0x03, ODT_REC, &ODObjs.o_1400_RPDOCommunicationParameter, NULL},
    {0x1600, 0x05, ODT_REC, &ODObjs.o_1600_RPDOMappingParameter, NULL},
    {0x1800, 0x07, ODT_REC, &ODObjs.o_1800_TPDOCommunicationParameter, NULL},
    {0x1A00, 0x04, ODT_REC, &ODObjs.o_1A00_TPDOMappingParameter, NULL},
    {0x2000, 0x01, ODT_VAR, &ODObjs.o_2000_ACTION_ID, NULL},
    {0x2001, 0x01, ODT_VAR, &ODObjs.o_2001_param_1, NULL},
    {0x2002, 0x01, ODT_VAR, &ODObjs.o_2002_param_2, NULL},
    {0x2003, 0x01, ODT_VAR, &ODObjs.o_2003_param_3, NULL},
    {0x2004, 0x01, ODT_VAR, &ODObjs.o_2004_param_4, NULL},
    {0x2005, 0x01, ODT_VAR, &ODObjs.o_2005_param_5, NULL},
    {0x2006, 0x01, ODT_VAR, &ODObjs.o_2006_param_6, NULL},
    {0x2007, 0x01, ODT_VAR, &ODObjs.o_2007_command_ID, NULL},
    {0x2100, 0x01, ODT_VAR, &ODObjs.o_2100_current_command_status, NULL},
    {0x2101, 0x01, ODT_VAR, &ODObjs.o_2101_current_command_id, NULL},
    {0x2102, 0x01, ODT_VAR, &ODObjs.o_2102_current_action_id, NULL},
    {0x2103, 0x01, ODT_VAR, &ODObjs.o_2103_last_completed_command_id, NULL},
    {0x2104, 0x01, ODT_VAR, &ODObjs.o_2104_command_error_code, NULL},
    {0x2200, 0x01, ODT_VAR, &ODObjs.o_2200_pos_robot_x, NULL},
    {0x2201, 0x01, ODT_VAR, &ODObjs.o_2201_pos_robot_y, NULL},
    {0x2202, 0x01, ODT_VAR, &ODObjs.o_2202_pos_robot_theta, NULL},
    {0x2203, 0x01, ODT_VAR, &ODObjs.o_2203_lin_vel_robot, NULL},
    {0x2300, 0x01, ODT_VAR, &ODObjs.o_2300_pos_robot_adversaire_x, NULL},
    {0x2301, 0x01, ODT_VAR, &ODObjs.o_2301_pos_robot_adversaire_y, NULL},
    {0x2302, 0x01, ODT_VAR, &ODObjs.o_2302_status_carte_lidar, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _OD = {
    (sizeof(ODList) / sizeof(ODList[0])) - 1,
    &ODList[0]
};

OD_t *OD = &_OD;
